version: '3'

services:
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    environment:
      - DATABASE_URL=file:/usr/src/app/prisma/tiendamia.db
    volumes:
      - ./server/prisma:/usr/src/app/prisma

  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - server